// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwnmppqpbtpknmikwajq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3bm1wcHFwYnRwa25taWt3YWpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMDc0MzYsImV4cCI6MjA2MTU4MzQzNn0.loW7gds6w6KjjEqjze4lBo6aXM_Mt_17ZwFtARrpBIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);